### PR TITLE
fix: upgrade storyblok richtext resolver to v2.1

### PR DESCRIPTION
**Pull request by rversantos**
Upgrades `storyblok/richtext-resolver` to version 2.1 which fixes [some bugs](https://github.com/storyblok/storyblok-php-richtext-renderer/releases/tag/2.1.0).

### CODE REVIEW

**Comment by divan-mt** [comment]
@RicLeP most of our projects that uses laravel-storyblok package has this issue and breaks the entire page.
I would appreciate so much if this gets merged. Right now the only way to fix our problem is to fork your package and bump the version manually. 
Thank you for your awesome work.

**Comment by RicLeP** [comment]
I'll test this tomorrow and should have a release ready for you! Thanks for the PR

**Comment by divan-mt** [comment]
Thank you so much for all the work you do.

**Comment by rversantos** [comment]
@RicLeP thank you a lot!

**Pull request merged**
